// get all projects, with optional sorting
GET http://localhost:3001/projects?sortBy=createdAt&order=desc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGQ3ZDMzZGMwYTQ3NWEzYzIxODBmNmIiLCJlbWFpbCI6InRlc3R0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY2NjQzMDM2LCJleHAiOjE3NjY3Mjk0MzZ9.8NmqHCmwXahbmRL2rwezxWU2xgrWzomDIZNXIiGbCew
GET http://localhost:3001/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGQ3ZDMzZGMwYTQ3NWEzYzIxODBmNmIiLCJlbWFpbCI6InRlc3R0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY2ODIyMjU5LCJleHAiOjE3NjY5MDg2NTl9.ctMnVCigNo8pbq2KNhz_TANVB0CquyqKMjPleydXHXc

// get a specific project by its ID
GET http://localhost:3001/projects/68e8cbaa4d99c5f34c200f48
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGQ3ZDMzZGMwYTQ3NWEzYzIxODBmNmIiLCJlbWFpbCI6InRlc3R0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY3MzU5ODg1LCJleHAiOjE3Njc0NDYyODV9.YGQ-c-x7QQi9NGDJ0UowxJ4r8lL2vM5Y4c97vlqJm_w